// ============================================================
// employee.model.ts
// Defines the TypeScript INTERFACE for an Employee.
// An interface is a contract — it says "any object called Employee
// MUST have exactly these fields with these types."
// TypeScript uses this for type-checking throughout the app.
// ============================================================

export interface Employee {
  id: string;                          // Unique UUID generated by backend
  name: string;                        // Full name
  email: string;                       // Work email
  phone: string;                       // Contact number
  department: Department;              // One of the allowed departments
  role: Role;                          // One of the allowed roles
  salary: number;                      // Annual salary (number, not string)
  joiningDate: string;                 // ISO format: "YYYY-MM-DD"
  status: 'active' | 'inactive';       // Union type — only these two values allowed
}

// ─────────────────────────────────────────────────────────────────
// Department type — restricts the department field to known values.
// TypeScript will give an error if you try to assign "Accounting" (not in list).
// ─────────────────────────────────────────────────────────────────
export type Department =
  | 'Engineering'
  | 'HR'
  | 'Sales'
  | 'Finance'
  | 'Marketing';

// ─────────────────────────────────────────────────────────────────
// Role type — same idea, restricts role to known values
// ─────────────────────────────────────────────────────────────────
export type Role =
  | 'Manager'
  | 'Developer'
  | 'Designer'
  | 'Analyst'
  | 'Intern';

// ─────────────────────────────────────────────────────────────────
// CreateEmployeeDto (Data Transfer Object)
// Used when CREATING a new employee — the id field is omitted
// because the backend generates it automatically.
// Omit<Employee, 'id'> = "Employee without the id field"
// ─────────────────────────────────────────────────────────────────
export type CreateEmployeeDto = Omit<Employee, 'id'>;

// ─────────────────────────────────────────────────────────────────
// UpdateEmployeeDto
// Used when UPDATING — all fields are optional (Partial<>)
// because the user might only change one field at a time.
// Partial<Employee> = "Employee where every field is optional"
// ─────────────────────────────────────────────────────────────────
export type UpdateEmployeeDto = Partial<Omit<Employee, 'id'>>;

// ─────────────────────────────────────────────────────────────────
// Constants for dropdowns in the form
// Keeping them here means if you add "Operations" later,
// you only update this one place.
// ─────────────────────────────────────────────────────────────────
export const DEPARTMENTS: Department[] = [
  'Engineering', 'HR', 'Sales', 'Finance', 'Marketing'
];

export const ROLES: Role[] = [
  'Manager', 'Developer', 'Designer', 'Analyst', 'Intern'
];
